<?php
ale_demo_media::add_image_to_media_gallery('ale_home1',"http://alethemes.com/olins_base/media/cosushi/home1.jpg");
ale_demo_media::add_image_to_media_gallery('ale_home2',"http://alethemes.com/olins_base/media/cosushi/home2.png");
ale_demo_media::add_image_to_media_gallery('ale_home3',"http://alethemes.com/olins_base/media/cosushi/home3.jpg");
ale_demo_media::add_image_to_media_gallery('ale_video',"http://alethemes.com/olins_base/media/cosushi/video.jpg");
ale_demo_media::add_image_to_media_gallery('ale_contact',"http://alethemes.com/olins_base/media/cosushi/contact.png");
ale_demo_media::add_image_to_media_gallery('ale_testy',"http://alethemes.com/olins_base/media/cosushi/testy.jpg");
ale_demo_media::add_image_to_media_gallery('ale_testy2',"http://alethemes.com/olins_base/media/cosushi/testy2.png");
ale_demo_media::add_image_to_media_gallery('ale_homebg',"http://alethemes.com/olins_base/media/cosushi/homebg.png");